apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: woodpecker-secrets
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: woodpecker-secrets
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_CLIENT
      remoteRef:
        key: homelab/woodpecker
        property: GITHUB_CLIENT
    - secretKey: GITHUB_SECRET
      remoteRef:
        key: homelab/woodpecker
        property: GITHUB_SECRET
    - secretKey: AGENT_SECRET
      remoteRef:
        key: homelab/woodpecker
        property: AGENT_SECRET
    - secretKey: VAULT_TOKEN
      remoteRef:
        key: homelab/woodpecker
        property: VAULT_TOKEN
    - secretKey: PROMETHEUS_AUTH_TOKEN
      remoteRef:
        key: homelab/woodpecker
        property: PROMETHEUS_AUTH_TOKEN
