apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gh-org-github-token
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: gh-org-github-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: homelab/gh-org
        property: github_token
    - secretKey: tofu_state_access_key_id
      remoteRef:
        key: homelab/gh-org
        property: TOFU_STATE_ACCESS_KEY_ID
    - secretKey: tofu_state_secret_access_key
      remoteRef:
        key: homelab/gh-org
        property: TOFU_STATE_SECRET_ACCESS_KEY
